###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm
HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
#MAGNETIC  =   magnetic
#RADIATION =   radiation_ray
FORCING   =   forcing
VISCOSITY =   viscosity
EOS       =   eos_idealgas
GRAVITY   =   gravity_simple
FOURIER   =   fourier_fftpack
POWER     =   power_spectrum
REAL_PRECISION = double
